### ISSUE TITLE
Can't relocate to registry with a port

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/kbld#100]
**What steps did you take:**
```
kbld relocate -f .imgpkg/images.yml --lock-output /tmp/output.lock --repository localhost:5000
```

**What happened:**
> kbld: Error: Building import repository ref: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: localhost:5000

**What did you expect:**
This should work, I don't know why there should be this regex constraining the repository

**Environment:**

- kbld version (use `kbld --version`): 0.29.0
- Docker registry used (e.g. `Docker HUB`):  https://hub.docker.com/_/registry

**Comment by joaopapereira** [comment]
Hey, @benmoss we are deprecating (#92) the relocate functionality on `kbld` and pointing people to start using [imgpkg](https://carvel.dev/imgpkg).
Do you see any particular reason why you would not be able to use `imgpkg` instead of `kbld`?

**Comment by benmoss** [comment]
Nope, that was one of the more confusing parts about kbld and imgpkg, so glad to see it being cleared up.

**Comment by cppforlife** [comment]
for the record if you are trying to relocate things into registry then you have to provide repository location e.g. `--repository localhost:5000/my-stuff/` (otherwise we do not know where to place things and underlying libraries will think that :5000 is a tag for localhost image)

**Comment by benmoss** [comment]
ah yes that was the problem, not the port. thanks!
