### ISSUE TITLE
kbld depends on vendir "versions" package, that doesn't exist any more

### ISSUE THREAD

**Issue by jpeach** [carvel-dev/kbld#106]
kbld has a dependency on github.com/vmware-tanzu/carvel-vendir/pkg/vendir/versions@v0.14.1-0.20201119204632-393bea7fb738

The `versions` package was removed from vendir  in 62ad5bc4e35be20d937f07fe960da724fdd2c8f0, so you can't build against vendir 0.17

**Comment by cppforlife** [comment]
it got moved here: https://github.com/vmware-tanzu/carvel-vendir/tree/develop/pkg/vendir/versions/v1alpha1.

**Comment by StevenLocke** [comment]
Thanks for pointing out the change! We'll get that upgrade into kbld soon, and we made a PR to track it.

In the meantime, if you need to build against vendir v0.17.0, take a look at the PR (#107) for an example. It's not too bad, mostly just changing the version in go.mod and naming the v1alpha1 package import.
