### ISSUE TITLE
kbld integration with bazel for building imgpkg bundles. 

### ISSUE THREAD

**Issue by mohansitaram** [carvel-dev/kbld#128]
**Describe the problem/challenge you have**
We are currently using bazel to build docker images from source code. We are also using helm charts and imgpkg bundles to package all application code and config. The challenge we are facing is this: Given an application that has a helm chart and bazel rules for building its docker images, how do we create an imgpkg bundle for it?

**Describe the solution you'd like**

There are a couple of ways to do this:

1. No direct integration between kbld and bazel:  
- Build image using bazel directly and push this image to an intermediate registry. 
- Update helm chart to use the above image. Then build imgpkg bundle for the application.
2. With kbld and bazel integration: 
- kbld calls bazel and builds the docker image. 
- kbld rewrites the image reference in the helm chart to point to the docker image on the local docker engine (i.e. the image that gets built using bazel in previous step). Then build imgpkg bundle for the application. 

**Anything else you would like to add:**
We could write custom tooling around kbld and bazel to implement solution 1 but solution 2 would be ideal. That is a solution in which kbld provides config or hooks wherein we can specify the location of the bazel config to use for building images.

We would also like to avoid the push of the docker images to the intermediate registry. The docker images would be already built using bazel and available on the local docker engine so it would be great if there is a way to use kbld to overwrite image references in helm charts to point to the local images. I believe this is already possible with other tools like pack and buildkit but I have not used those tools so I could be wrong. 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
Hi @mohansitaram, thank you for surfacing this idea. I can see how the streamlined workflow in the second scenario that you proposed would be an improvement. Personally, I'm not very familiar with bazel but if I understand your use then it feels similar to the way that kbld currently [allows different build sources (such as docker, pack, buildkit, ko)](https://carvel.dev/kbld/docs/latest/config/#sources). Would you expect that kbld would only need to run any commands other than `bazel build`?

> We would also like to avoid the push of the docker images to the intermediate registry.

I think that this piece would require a bit more investigation on our end. I suspect that we'd be able to extend [`destinations`](https://carvel.dev/kbld/docs/latest/config/#destinations) for this but we'd need to think about it more holistically.

@cppforlife do you have any thoughts on this request?

**Comment by mohansitaram** [comment]
@aaronshurley yes it would be great if bazel is another build tool that kbld can support similar to docker, pack, ko, etc. I can imagine a solution like this: 

- kbld is given a kubernetes yaml file for an application. The yaml file has image references.
- There is also another (new) config file that has bazel config to build images mentioned in above yaml file.
- kbld calls bazel build <bazel target> to build those images (I don't expect kbld to call any other bazel commands)
- kbld generates an image lock file containing the images built using bazel. 

Then we can create an imgpkg bundle for this and push it to a registry and deploy the application. Something like this would help greatly with quick dev/testing. Say you change source code and you want to build an image out of it and deploy your change to a cluster, such an integration between kbld and bazel would be extremely useful.

**Comment by cppforlife** [comment]
@mohansitaram given your experience with bazel would you be interested in contributing support for this builder? it sounds like it might be something similar to either https://github.com/vmware-tanzu/carvel-kbld/blob/develop/pkg/kbld/image/built.go#L57-L60 (builtkit-on-k8s builds and pushes images in one go) or https://github.com/vmware-tanzu/carvel-kbld/blob/develop/pkg/kbld/image/built.go#L63-L68 (ko builds within docker daemon, and kbld orchestrates separate push)

> if there is a way to use kbld to overwrite image references in helm charts to point to the local images.

im not exactly sure about this bit. do you want your final references to just be images in docker daemon? who would push them and when?

**Comment by mohansitaram** [comment]
@cppforlife Our team would certainly like to contribute. We will figure out the staffing needs and get back to you on this. 

> im not exactly sure about this bit. do you want your final references to just be images in docker daemon? who would push them and when?

I was thinking that we create the imgpkg bundle using the images from docker daemon. And when we push the bundle to the destination registry it also pushes the images. Similar to the imgpkg copy workflow using a tar file that has both yaml and image. As far as who pushes it, it could be either kbld or something out of band. 

So there might be two ways of doing this:

1. Create an imgpkg bundle tarfile from K8s yaml manifest from local filesystem and docker image from local docker engine. Then push this tar file to destination registry.
2. Push images from local docker engine to destination registry. Then create an imgpkg bundle (with image references pointing to destination registry) and push bundle to destination registry. 

We would like 1) using the tar file because that would keep our development workflow and production workflow (airgapped env) similar. 

For 2) seems like from the links to code you sent kbld already has support for pushing images to registries. That is an option too. I don't know which option would be faster and easier to implement though. Please also let me know if I'm assuming things that might be non-starters in my suggestions.

**Comment by cppforlife** [comment]
> I was thinking that we create the imgpkg bundle using the images from docker daemon

imgpkg does require that images referenced in images.yml are in the registry (it wants a fully resolved digest ref), so i dont think imgpkg would be applicable here.

option (2) is the simplest to implement because that's what other builders do as well. also given the statement above about imgpkg needing full registry refs.

if you are trying to get to an imgpkg bundle, my current recommendation is the following flow:

```
kbld -f ./stuff.yml -f ./config.yml --imgpkg-lock-output .imgpkg/images.yml
imgpkg push -b my-bundle -f .
```

assuming kbld is configured to build and push, it would record digest refs that were pushed by docker daemon. and imgpkg would push up a bundle with those refs in the next step.

**Comment by cliuj** [comment]
Hey @cppforlife , @aaronshurley , @mohansitaram , I'm currently working on a bazel builder support for option 2. I will keep you guys updated with the results.

**Comment by pivotaljohn** [comment]
Updated issue to reflect current state. PR is waiting for review, now.

**Comment by pivotaljohn** [comment]
Done.

**Comment by cppforlife** [comment]
@cliuj really nice work on getting this integrated!
