### ISSUE TITLE
Build and install Apple Silicon-targeted versions of kbld

### ISSUE THREAD

**Issue by pivotaljohn** [carvel-dev/kbld#143]
see vmware-tanzu/carvel#218

Do it like we do for ytt.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by DennisDenuto** [comment]
Next release 0.31.0 will contain an arm binary.

When updating the homebrew and install.sh, remember to also now include a reference to the arm binary
