### ISSUE TITLE
kbld v0.31.0

### ISSUE THREAD

**Issue by aaronshurley** [carvel-dev/kbld#147]
- [x] Create release in Github
    - [x] [Bump Version](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Bump-version)
- [x] [Create an OSM Release](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#OSM-Release)
    - [x] [Create a Github release](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Create-a-Github-Release)
    - [x] [Create the Release Notes](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Create-the-Release-Notes)
    - [x] [Generate Binaries and Checksum](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Generate-Binaries-and-Checksum)
- [x] Close any GitHub issues that have been delivered.
  - [x] Add a link to the release on the issue.
- [x] Update the packaging repositories
    - [x] [Update Homebrew](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Update-Homebrew)
    - [x] ~[Update Chocolatey](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Update-Chocolatey)~
    - [x] [Update Github Action](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Update-Github-Action)
    - [x] [Update Website Installation Script](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Update-Website-Installation-Script)
- Publish to TanzuNet 
    - [x] (`ytt`, `kapp`, `kbld`, `imgpkg`) Ensure [pivnet-sync](https://hush-house.pivotal.io/teams/k8s-lifecycle-tools/pipelines/pivnet-sync) publish to TanzuNet tasks succeeded. ([pipeline source](github.com/pivotal/k8s-lifecycle-tools-ci))
- [x] [Communicate in Slack](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Communicate-in-Slack)
- [x] [Add to "Announcements" in Next Community Meeting Agenda](https://hackmd.io/uVpvITUuR4Cbwzkzb7MEpQ?view#Announce-in-community-meeting)

**Comment by pivotaljohn** [comment]
- #128 
  added as ZH dependency: it's close to landing.
