### ISSUE TITLE
dx: show help page by default

### ISSUE THREAD

**Issue by Dentrax** [carvel-dev/kbld#184]
**Describe the problem/challenge you have**
To improve developer experience for the fresh installations, It think It had better to show _help_ page instead of print out `Succeeded`.

```bash
$ kbld
Succeeded
```

**Describe the solution you'd like**
```bash
$ kbld
# show help page by default
```

```bash
$ kbld --help

<HELP MESSAGE HERE>

Succeeded
```

**Anything else you would like to add:**
I think we should not print out `Succeeded` log at the end of each output. Wdyt?

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
Thank you, @Dentrax, for calling this out.

In fact, with the Carvel project, there's a greater issue of an inconsistent behavior.

I created an issue in the umbrella repository: vmware-tanzu/carvel#290 to track the broader question.

Will close _this_ issue to keep the conversation about these thing over there.

Thanks again! 🙏🏻
