### ISSUE TITLE
Is it possible to package images by themselves?

### ISSUE THREAD

**Issue by johnSchnake** [carvel-dev/kbld#231]
**Describe the problem/challenge you have**
Working with k8s e2e testing means needing a series of test images available to the cluster. I do not have manifets/pod definitions for these, they are generated at runtime. I want to make sure those images are still prepulled and available to the cluster even in an airgapped environment.

**Describe the solution you'd like**
I'd like to use kbld and imgpkg to resolve/store the list if images as if they were part of a deployment; I just want to be able to push/pull those around as a bundle even though there aren't any k8s resources that actually utilize them in the bundle.

**Anything else you would like to add:**
Probably the easiest way to describe this would be:

"I want a nway to prepull a list of images into the cluster without necessarily creating any other k8s resources"

I see that imgpkg can resolve tags, but it doesn't build the imagelock file like kbld so I assumed this question/ask would belong here.

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
> I want a nway to prepull a list of images into the cluster without necessarily creating any other k8s resources

how would you expect cluster to "prepull" images? that's not something that can be done to my knowledge without some resource (like a Pod) be created in the cluster (so that k8s knows what to pull).

**Comment by johnSchnake** [comment]
Sorry, I conflated two different things. I don't necessarily mean prepulling the images into the cluster itself (e.g. onto the nodes) but moving them into an airgapped registry, reachable from the cluster.

I want to be able to move the images that I know I will need in the future, but I don't have the workloads at all, the testing code generates those.

**Comment by johnSchnake** [comment]
Sorry, I conflated two different things. I don't necessarily mean prepulling the images into the cluster itself (e.g. onto the nodes) but moving them into an airgapped registry, reachable from the cluster.

I want to be able to move the images that I know I will need in the future, but I don't have the workloads at all, the testing code generates those.

**Comment by johnSchnake** [comment]
FWIW I found that if, when making my bundle, I include another file of "virtual resources" which are just
```
spec:
  image: <img>
```
It resolves and saves the images as expected. Just later, when deploying, I ignore any files like that.

So it seems like it would be sufficient if there were another type which kbld would filter out of the resulting stream (like it does the config types) that can take a list of images. It would still be processed by the stream, resolved, and included in any thick copy but it wouldn't get in the way of any actual deployments.

**Comment by cppforlife** [comment]
> I include another file of "virtual resources" which are just

yeah, kbld doesnt care that input yaml is a kubernetes resource. i recommend folks sometimes to use this format:

```
images:
- image: x
- image: y
```

to just let kbld know about a set of images.

**Comment by johnSchnake** [comment]
Thats perfect; thanks for the sanity check.
