### ISSUE TITLE
Ability to produce multi-arch images with Docker (image indexes/manifest lists)

### ISSUE THREAD

**Issue by benmoss** [carvel-dev/kbld#239]
**Describe the problem/challenge you have**
I'd like to produce a [manifest image index](https://github.com/opencontainers/image-spec/blob/02efb9a75ee11e05937b535cc5f228f9343ab2f5/image-index.md) so that my image can work for multiple platforms

**Describe the solution you'd like**
Docker [can build manifest lists](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) through the `docker buildx` commands. 

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by cppforlife** [comment]
x-ref: https://github.com/vmware-tanzu/carvel-kbld/pull/244
