### ISSUE TITLE
Add apko as a Builder

### ISSUE THREAD

**Issue by pivotaljohn** [carvel-dev/kbld#264]
**Describe the problem/challenge you have**
apko provides fast, reproducible OCI image builds.

It's a tool from https://www.chainguard.dev/ — some of the same folks that started Sigstore.

**Describe the solution you'd like**
Write a builder for apko so that Carvel users can enjoy the benefits of apko.

**Anything else you would like to add:**
The source of apko-produced OCI images are Alpine packages (APKs). The same group provides a tool to produce APKs: https://github.com/chainguard-dev/melange

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment]
Saw this "[advertised](https://twitter.com/puerco/status/1542018385550123008?s=21)".  Created this issue to make it easy for our users to let us know they want/are using apko.

**Comment by aaronshurley** [comment]
Reopening this issue but will label as awaiting more evidence
