### ISSUE TITLE
add railwayapp/nixpacks as a builder

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kbld#266]
**Describe the problem/challenge you have**
https://github.com/railwayapp/nixpacks would be a useful builder to include.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen. If applicable a visual representation of the UX (ex: new CLI argument name, the behavior expected).]

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by aaronshurley** [comment]
Reopening this issue but labeling as awaiting for more evidence
