### ISSUE TITLE
ensure that kbld.k14s.io/images annotations is deterministically ordered

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kbld#34]
to avoid unnecessary annotation changes

**Comment by jbrunton** [comment]
@cppforlife: I have a bit of time and I'm looking to contribute to more OS projects. Any objections if I have a go at this? It might also pair up with #18 quite well.

**Comment by cppforlife** [comment]
@jbrunton sounds good! it's all yours.

**Comment by jbrunton** [comment]
@cppforlife: Thanks for the merging the PR! Can this issue be closed now too?

**Comment by cppforlife** [comment]
@jbrunton i typically close all in-progress issues once they are included in a release. im planning to cut a new kbld version wed/thurs, so ill close it then.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/kbld/releases/tag/v0.24.0
