### ISSUE TITLE
pushing images that are not being built

### ISSUE THREAD

**Issue by jan-hudec** [carvel-dev/kbld#35]
I have the images already built by the CI server, but due to technical reasons the production environment does not see the registry where it is.

kbld can both pull (when packaging) and push (after building) images. But can I use it to just push the images to the target registry without processing the manifest multiple times and creating the intermediate tar? The server running the deployment does see both registries, so I don't really need a package.

I tried using just `ImageDestinations` with no sources and setting `imageRepo` to the name without tag, but it didn't seem to work.

**Comment by pivotaljohn** [comment]
I _think_ I understand the thrust of your question...

Are you asking if there's a way to copy/relocate an image from one registry into another, directly (i.e. without needing to create a tarball)?

**Comment by jan-hudec** [comment]
@pivotaljohn, yes.

**Comment by pivotaljohn** [comment]
That exact feature is under development, right now.

To clarify, `ImageDestinations` is used [when resolving an image reference requires that that image be built and pushed](https://github.com/k14s/kbld/blob/v0.22.0/pkg/kbld/image/factory.go#L39). In that case, the `Sources` configuration points to where the code can be found and `ImageDestinations` points to where the built image can be pushed.

**Comment by cppforlife** [comment]
https://github.com/k14s/kbld/releases/tag/v0.23.0 includes `kbld relocate` command that copies images without having to make a local tar.
