### ISSUE TITLE
 Enhance kbld to Utilize Alternative Image Operations Mechanism

### ISSUE THREAD

**Issue by ceprateek** [carvel-dev/kbld#415]
**Describe the problem/challenge you have**
In our current workflow, `kbld` builds the `container_image` target using Bazel and manages the image (loading, tagging, and pushing) by parsing the SHA from Bazel’s output, inherently relying on the Docker daemon. While this approach is functional for local builds, it introduces performance and concurrency challenges in a build system where multiple builds utilize a shared remote Docker host and the Bazel cache operates on a different host.

**Describe the solution you'd like**
We propose an enhancement to `kbld` to support image operations (build, tag, push) through mechanisms other than the Docker daemon. Specifically, we suggest exploring a feature similar to Bazel's `container_push` target, which internally uses `crane` for image operations without a Docker daemon dependency ([crane push documentation](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_push.md)).

This enhancement would:
- **Remove** the dependency on the Docker daemon, mitigating the aforementioned performance and concurrency issues.
- **Potentially streamline** and optimize the image build and push process, especially in environments with separate hosts for Docker and Bazel cache.

**Anything else you would like to add:**
**Background:** 
- The current `kbld` process builds the image, extracts the SHA from Bazel’s output, and manages (load, tag, push) the image, all through the Docker daemon.
- This Docker daemon dependency is suboptimal in scenarios involving remote Docker hosts and separate Bazel cache hosts, impacting performance and concurrency.

**Challenge:** 
- The Docker daemon dependency is not conducive for scalable and efficient operations in our build system, which involves multiple builds, a shared remote Docker host, and a distinct host for Bazel cache.

We believe that this enhancement will not only address our current challenges but also benefit other `kbld` users who might be in a similar situation or are looking for a Docker daemon-agnostic image management approach.

Thank you for considering this feature request. We are looking forward to your feedback and are open to contributing to the development of this feature.

**Comment by joaopapereira** [comment]
We could add this feature, but we would need to understand if Bazel provides any output that kbld can interpret as the image being uploaded or not. Do you know what the output would look like in this case, @ceprateek ?
