### ISSUE TITLE
kbld does not error given an unknown command

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kbld#45]
Kbld reports success given an unknown command.

```
workspace/kbld » kbld i-dont-exist
Succeeded
```

This should error telling the user that `i-dont-exist` is an unknown command

**Comment by Zebradil** [comment]
#33 is about the same, I guess.

**Comment by ewrenn8** [comment]
Yep, thanks for pointing that out! I will close this one as #33 has more context.
