### ISSUE TITLE
support uploading kbld built images to tags

### ISSUE THREAD

**Issue by ewrenn8** [carvel-dev/kbld#52]
For convenience, it may be helpful to allow the `destination.newImage` field of an `ImageDestination` document to contain a tag. Currently it errors when trying to auto-generate the upload tag

**Comment by cppforlife** [comment]
i think it's probably better to have a separate tags field that will be an array. since a lot of times you may want to add multiple tags at once (e.g. `tags: ["1-latest", "1.0.1"]`)

**Comment by StarpTech** [comment]
Would you accept a PR? When yes could you make a configuration example?

**Comment by StarpTech** [comment]
I think the easiest solution would be to pass additional tags to https://github.com/k14s/kbld/blob/5baf1d5fefa9a76ce8d46556c376ec9d8662e0f9/pkg/kbld/image/docker.go#L95

**Comment by cppforlife** [comment]
included in https://github.com/k14s/kbld/releases/tag/v0.26.0

**Comment by StarpTech** [comment]
Nice, thanks!
