### ISSUE TITLE
Docs deviation: Config, ImageOverrides and --lock-output

### ISSUE THREAD

**Issue by Zebradil** [carvel-dev/kbld#58]
`kbld --lock-output` produces a file with a resource of `Config` kind.  
But in [the docs](https://github.com/k14s/kbld/blob/v0.23.0/docs/config.md) I don't see a mention that `kind: Config` has `overrides` key.

I'd like to clarify which `kind` is preferable for overriding images: `ImageOverrides` or `Config`. 

Here is a snippet I used for testing:
```sh
echo "image: postgres" | kbld -f - --lock-output /dev/fd/2 > /dev/null
resolve | final: postgres -> index.docker.io/library/postgres@sha256:8f7c3c9b61d82a4a021da5d9618faf056633e089302a726d619fa467c73609e4
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.23.0
overrides:
- image: postgres
  newImage: index.docker.io/library/postgres@sha256:8f7c3c9b61d82a4a021da5d9618faf056633e089302a726d619fa467c73609e4
  preresolved: true
```

**Comment by cppforlife** [comment]
@Zebradil some time ago ive introduced Config kind which actually covers all the config (sources, destinations, etc.). since we want to be backwards compatible we will not remove dedicated kinds (e.g. Sources); however, going forward we will not be creating dedicated kinds. we should probably update docs to indicate that you can use kind Config for all configuration.

**Comment by Zebradil** [comment]
So, if I understand correctly, using Config kind is preferable. Thanks a lot!

(Not sure if I should close the issue or it'll be closed after docs update)

**Comment by pivotaljohn** [comment]
Leaving this open is perfect, @Zebradil; thank you.

@cppforlife does this match how you're thinking?:

1. in the main flow in the docs, replace all references to other configuration files (i.e. `kind: Sources`, `kind: ImageDestinations`, etc) with `kind: Config`
2. footnote in those various places that a deprecated way to express those configurations _was_ by using those specific kinds.

**Comment by cppforlife** [comment]
updated https://github.com/vmware-tanzu/carvel-kbld/blob/develop/docs/config.md.
