### ISSUE TITLE
Is vendor directory used?

### ISSUE THREAD

**Issue by StarpTech** [carvel-dev/kbld#64]
Hi, the vendor dir isn't in sync. Do we use `vendoring` in this project?

**Comment by cppforlife** [comment]
`go mod vendor` runs everytime we build: https://github.com/vmware-tanzu/carvel-kbld/blob/develop/hack/build.sh#L10. what do you see out of sync?

**Comment by StarpTech** [comment]
When I run `go mod vendor` a lot of files are added.

**Comment by danielhelfand** [comment]
Thanks for reporting this @StarpTech. We were able to also confirm vendor appears to be out of sync and opened a pr to resolve this. Please feel free to review and provide feedback on it.

One thing maybe we should consider in the future is having something as part of the CI to verify vendor is in sync to make sure we are not checking things in without properly updating vendor.

**Comment by cppforlife** [comment]
LOL i think i finally realized what happened. PR https://github.com/vmware-tanzu/carvel-kbld/pull/62 did not include result of updated vendor/ dir after ./hack/build.sh hence vendor directory didnt include appropriate dependencies. 

> One thing maybe we should consider in the future is having something as part of the CI to verify vendor is in sync to make sure we are not checking things in without properly updating vendor.

yes! if after build directory is dirty we should error in CI.

@StarpTech tip for future, run ./hack/build.sh and check out what files were modified ;)

**Comment by StarpTech** [comment]
What's with https://github.com/vmware-tanzu/carvel-kbld/pull/66#issuecomment-729272967

**Comment by danielhelfand** [comment]
> What's with [#66 (comment)](https://github.com/vmware-tanzu/carvel-kbld/pull/66#issuecomment-729272967)

I am not familiar with Go proxies, but they seem to be the suggested alternative to vendoring. Vendoring helps with assuring dependencies are available in the event remote repositories no longer exist. If we want to explore approaches with Go proxies, I would suggest opening an issue to formerly discuss it.

@cppforlife Any other context to provide on this?
