### ISSUE TITLE
Support for using alternative image repo when resolving or replace image repo after resolve

### ISSUE THREAD

**Issue by hulucc** [carvel-dev/kbld#77]
When resolving image, I need the public url of registry(resolve outside k8s cluster), but need private url of registry at runtime for better performance.
`cnab-image-relocation` can't not replace image repo only and override in config will cause resolve fail.

**Comment by danielhelfand** [comment]
Thanks for reporting this @hulucc. Would you be able to put together a simple example of how you are using `kbld` and `cnab-image-relocation` such that you are getting this failure?
