### ISSUE TITLE
Option to preserve path and name when relocating images

### ISSUE THREAD

**Issue by jimconner** [carvel-dev/kbld#79]
**Describe the problem/challenge you have**

I'm deploying cf-for-k8s using kbld to relocate images to a harbor registry. 
cf-for-k8s has takes images from many sources
e.g.
``` 
- image: index.docker.io/cloudfoundry/cf-api-package-registry-buddy@sha256:87a6c4d2ec14d97f8c193a6b8dd2c26926eaa78eb85052997ae55cbb34880ad0
- image: index.docker.io/cloudfoundry/cloud-controller-ng@sha256:00d4a985180b4a79c325860119aecd33af0fd06f2e2e9a49a375c9bad0b0b988
- image: index.docker.io/logcache/log-cache-cf-auth-proxy@sha256:c37c1065f026aba7b581f357a9d4268c8724a93630184b76307343195370d0cb
- image: gcr.io/cf-routing/pilot@sha256:dc3ae4f4a5b30828d4d92e879c698fd56d898e5755fad07fcbc1e25227062eba
- image: gcr.io/paketo-buildpacks/go@sha256:913f17254fea069c8ff8b1e47e6367dec689a7ecc497be1a30fd8f042a1daf26
```
From the above we can easily work out which image is for which component as the project name and image name are contained within the path.

After relocation to my.private.registry/cf-images we've rendered the human-readable parts meaningless:
```
- newImage: my.private.registry/cf-images/cf-image@sha256:87a6c4d2ec14d97f8c193a6b8dd2c26926eaa78eb85052997ae55cbb34880ad0
- newImage: my.private.registry/cf-images/cf-image@sha256:00d4a985180b4a79c325860119aecd33af0fd06f2e2e9a49a375c9bad0b0b988
- newImage: my.private.registry/cf-images/cf-image@sha256:c37c1065f026aba7b581f357a9d4268c8724a93630184b76307343195370d0cb
- newImage: my.private.registry/cf-images/cf-image@sha256:dc3ae4f4a5b30828d4d92e879c698fd56d898e5755fad07fcbc1e25227062eba
- newImage: my.private.registry/cf-images/cf-image@sha256:913f17254fea069c8ff8b1e47e6367dec689a7ecc497be1a30fd8f042a1daf26
```

Harbor registry has in-built container vulnerability scanning, but the lack of human-readable image names make it hard to know which image is which. 

**Describe the solution you'd like**
A flag or option for relocate to preserve the name of the image in the target registry.

e.g. after relocation we'd have something like
```
- newImage: my.private.registry/cf-images/cf-api-package-registry-buddy@sha256:87a6c4d2ec14d97f8c193a6b8dd2c26926eaa78eb85052997ae55cbb34880ad0
- newImage: my.private.registry/cf-images/cloud-controller-ng@sha256:00d4a985180b4a79c325860119aecd33af0fd06f2e2e9a49a375c9bad0b0b988
- newImage: my.private.registry/cf-images/log-cache-cf-auth-proxy@sha256:c37c1065f026aba7b581f357a9d4268c8724a93630184b76307343195370d0cb
- newImage: my.private.registry/cf-images/pilot@sha256:dc3ae4f4a5b30828d4d92e879c698fd56d898e5755fad07fcbc1e25227062eba
- newImage: my.private.registry/cf-images/go@sha256:913f17254fea069c8ff8b1e47e6367dec689a7ecc497be1a30fd8f042a1daf26
```

This would help greatly with humans being able to understand which images is which within the registry.

**Anything else you would like to add:**
Along similar lines, it would be really useful to be able to define mappings from source-registry to destination-registry to allow for better grouping (again to assist with human interraction with registry maintenance).

Somthing along the lines of
```
registry_mappings=[
{"index.docker.io/logcache" : "my.private.registry/logcache"},
{"gcr.io/paketo-buildpacks"  : "my.private.registry/packeto-buildpacks"},
{"*" : "my.private.registry/cf-images"}]
```

This would allow the groupings of image-by-project to be maintained.

**Comment by cppforlife** [comment]
@jimconner we are planning to introduce functionality that would preserve "origin naming" as a tag (e.g. `index.docker.io/cloudfoundry/cf-api-package-registry-buddy` might be tagged as `cloudfoundry-cf-api-package-registry-buddy-<rand>`) as a middle-ground between preserving names and not doing anything at all.

in general we would much rather improve tracking of images and assigning metadata on the registry side instead of trying to deal with all kinds of "conflicts" in name mangling.

**Comment by jimconner** [comment]
Thanks for replying @cppforlife - Although I think that the 'origin naming' tagging idea is a good one which offers lots of opportunities when you're writing your own scripts/code, it wouldn't address my issue of making existing 3rd party tooling (such as image security scanners) present human readable reports. 

Working in heavily locked-down, audited, air-gapped environments with onerous security requirements means having to keep the security team happy, and that means working with an off-the-shelf container image vulnerability scanning solution which generates reports that the security team can understand. The same air-gapped environment gives us a private docker registry where we have full control over our namespaces and can avoid conflicts pretty easily.

A mechnaism for preserving names when relocating from public to private registry is a highly desirable feature for me.

**Comment by cppforlife** [comment]
> it wouldn't address my issue of making existing 3rd party tooling (such as image security scanners) present human readable reports.

do security scanners not include tags in the report?

**Comment by jimconner** [comment]
Yes, tags are included, but the way the information is presented/grouped makes it difficult to understand which image is which.

![harbor-scan](https://user-images.githubusercontent.com/9944861/101930565-39916b80-3bd0-11eb-8d62-12ce7ce89f5b.jpg)

**Comment by cppforlife** [comment]
separately, i think there is something to be said about scope of "discoverability". security scanner would indicate that there is an issue with `my.private.registry/cf-images/cf-image` (from your example). this indicates to whoever imported cf product that there is an issue with it --> need to update to cf product or submit a report (automated perhaps).

i would be very much interested in understanding workflow you go through with regards to updates and security scanning. if you would be willing to drop by #carvel channel on Kubernetes slack we could set up a zoom meeting?

**Comment by cppforlife** [comment]
> Yes, tags are included, but the way the information is presented/grouped makes it difficult to understand which image is which.

so if there would be a tag with a name instead of "kbld-sha256-..." that would be a step in right direction, right? another question that occurs to me is whether you are planning to import updates to CF into `my.private.registry/cf-images/cf-image` again. what about importing into `my.private.registry/cf-images/cf-image-vX` for each new version? that provides segregation of each new "product bundle" from UI perspective as well.

separately, would providing a command that lists latest vulnerability scans for images within a product bundle be helpful (im trying to tease out workflows that are being exercised in more automated ways since browsing through a registry isnt a scalable solution)?

**Comment by danielhelfand** [comment]
Removing the stale label. This was marked as discussion, which we skip for marking things stale. Due to a typo in our GitHub action, this was accidentally labeled stale.

**Comment by cppforlife** [comment]
closing here in favor of https://github.com/vmware-tanzu/carvel-imgpkg/issues/60 (kbld relocate functionality is superseded by imgpkg copy).
