### ISSUE TITLE
Hello from the Shipwright Community!

### ISSUE THREAD

**Issue by sbose78** [carvel-dev/kbld#89]
Hello everyone!

I'm one of the contributors to the [Shipwright](https://github.com/shipwright-io/build/)  project and wanted to say Hi 👋 since we are working on solving similar problems. 🍷 

Good wishes on your project!

Cheers,
Shoubhik

**Comment by danielhelfand** [comment]
Hi @sbose78,

Thanks for introducing the Shipwright project to us. We would be excited to collaborate further if there are mutual opportunities for Carvel/Shipwright. If you are interested in talking further about Carvel tools, feel free to join our [slack](https://kubernetes.slack.com/archives/CH8KCCKA5) channel on the Kubernetes slack.

Closing this for now, but looking forward to hearing more from you!
